// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableTree.Data;

#nullable disable

namespace TableTree.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241211200756_Products_DataSeeding")]
    partial class Products_DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TableTree.Data.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TableTree.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TableTree.Data.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1042fee-f95a-4bf3-a758-49b13cff3e79"),
                            Name = "Table"
                        },
                        new
                        {
                            Id = new Guid("61bc3294-73ca-441b-9b53-0d4f26b673f3"),
                            Name = "Bathroom Countertop"
                        },
                        new
                        {
                            Id = new Guid("6acd5822-a59e-4427-b8ac-fbca0751cd98"),
                            Name = "Mirrors"
                        });
                });

            modelBuilder.Entity("TableTree.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("TableTree.Data.Models.FavouriteProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("FavouriteProducts");
                });

            modelBuilder.Entity("TableTree.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TableTree.Data.Models.OrderItemInfo", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TableTree.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("/images/no-image.jpg");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TreeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TreeTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2de3a6b8-7891-49c6-96ee-10a3b73d2f48"),
                            CategoryId = new Guid("61bc3294-73ca-441b-9b53-0d4f26b673f3"),
                            Description = "A sturdy coffee table made from reclaimed pine with a rich, warm finish. Eco-friendly and unique, it brings warmth to any room.",
                            ImageUrl = "/images/table-1.jpeg",
                            IsDeleted = false,
                            Name = "Reclaimed Wood Counter Top",
                            Price = 450.00m,
                            TreeTypeId = new Guid("401dd5cd-c271-4960-84ce-0b364c96f039")
                        },
                        new
                        {
                            Id = new Guid("393006f7-9c37-4f7d-80c4-1db8c4ae7569"),
                            CategoryId = new Guid("a1042fee-f95a-4bf3-a758-49b13cff3e79"),
                            Description = "A unique epoxy resin table made from an olive tree. This coffee table was cast with turquoise semi-transparent epoxy resin and a touch of metallic powder, creating a beautiful turquoise water look. The fashionable stainless steel spider table frame completes the overall look of this coffee table.",
                            ImageUrl = "/images/table-2.jpeg",
                            IsDeleted = false,
                            Name = "Eris Hackberry Blue Epoxy Resin Table",
                            Price = 4800.00m,
                            TreeTypeId = new Guid("133a6af3-1b7d-4d6e-aa41-33be63184766")
                        },
                        new
                        {
                            Id = new Guid("b29522fe-0ea0-4a01-9513-ab5d9cab230b"),
                            CategoryId = new Guid("61bc3294-73ca-441b-9b53-0d4f26b673f3"),
                            Description = "A unique epoxy resin table made from an olive tree. This coffee table was cast with turquoise semi-transparent epoxy resin and a touch of metallic powder, creating a beautiful turquoise water look. The fashionable stainless steel spider table frame completes the overall look of this coffee table.",
                            ImageUrl = "/images/table-3.jpg",
                            IsDeleted = false,
                            Name = "Epoxy resin table olive tree",
                            Price = 1200.00m,
                            TreeTypeId = new Guid("401dd5cd-c271-4960-84ce-0b364c96f039")
                        },
                        new
                        {
                            Id = new Guid("cc1f88fd-382d-4003-85e9-2d831d87406b"),
                            CategoryId = new Guid("a1042fee-f95a-4bf3-a758-49b13cff3e79"),
                            Description = "Beautiful table featuring a blue resin river down the center, crafted from black walnut wood. Ideal for dining rooms.",
                            ImageUrl = "/images/table-4.jpeg",
                            IsDeleted = false,
                            Name = "Epoxy Resin River Table",
                            Price = 1199.50m,
                            TreeTypeId = new Guid("133a6af3-1b7d-4d6e-aa41-33be63184766")
                        },
                        new
                        {
                            Id = new Guid("47ac7201-236d-42b2-91bd-b3f57d0bf77e"),
                            CategoryId = new Guid("a1042fee-f95a-4bf3-a758-49b13cff3e79"),
                            Description = "A handcrafted table made from live-edge oak, showcasing natural wood grain and organic shape. Perfect as a centerpiece in any living space.",
                            ImageUrl = "/images/table-5.jpeg",
                            IsDeleted = false,
                            Name = "Rustic Live Edge Tree Table",
                            Price = 799.99m,
                            TreeTypeId = new Guid("632bfa2f-aa06-4c1b-913d-33ef43a44d34")
                        },
                        new
                        {
                            Id = new Guid("8bbd0d28-418d-40dc-b311-f254c29c1165"),
                            CategoryId = new Guid("6acd5822-a59e-4427-b8ac-fbca0751cd98"),
                            Description = "Adorn your living space with our exquisite Epoxy and Olive Wood Decorative Bathroom Mirror – a fusion of artistry and practicality that transcends ordinary decor. Crafted with meticulous attention to detail, this handmade masterpiece is more than just a mirror",
                            ImageUrl = "/images/mirror-1.jpg",
                            IsDeleted = false,
                            Name = "Custom Epoxy and Olive Wood Decorative Mirror",
                            Price = 99.99m,
                            TreeTypeId = new Guid("133a6af3-1b7d-4d6e-aa41-33be63184766")
                        },
                        new
                        {
                            Id = new Guid("6cfa25f3-22a1-472d-89f2-e1d90fa124ef"),
                            CategoryId = new Guid("6acd5822-a59e-4427-b8ac-fbca0751cd98"),
                            Description = "This special design, crafted from olive wood, has been meticulously prepared, preserving the natural edge and bark of the wood. The cracks have been filled with special epoxy, and a custom matte varnish has been applied to the wood surface to provide resistance against scratches without losing its natural texture",
                            ImageUrl = "/images/mirror-2.jpg",
                            IsDeleted = false,
                            Name = "Olive Wooden Wall Mirror, Wooden Mirror",
                            Price = 115.99m,
                            TreeTypeId = new Guid("401dd5cd-c271-4960-84ce-0b364c96f039")
                        },
                        new
                        {
                            Id = new Guid("db8be300-48be-4da7-85cd-3402c40882be"),
                            CategoryId = new Guid("61bc3294-73ca-441b-9b53-0d4f26b673f3"),
                            Description = "Elevate your bathroom with our handcrafted wooden countertop, made from sustainably sourced oak. Each piece is carefully treated for durability, offering a unique blend of natural beauty and modern functionality to complement any decor style.",
                            ImageUrl = "/images/bathroom-countertop-1.jpg",
                            IsDeleted = false,
                            Name = "Wooden bathroom countertop",
                            Price = 235.99m,
                            TreeTypeId = new Guid("401dd5cd-c271-4960-84ce-0b364c96f039")
                        },
                        new
                        {
                            Id = new Guid("e45a4684-87bc-49f4-846d-79c569a8520b"),
                            CategoryId = new Guid("61bc3294-73ca-441b-9b53-0d4f26b673f3"),
                            Description = "Transform your bathroom with this set of boutique natural wood countertops, expertly crafted from premium, sustainably sourced wood.",
                            ImageUrl = "/images/bathroom-countertop-2.jpg",
                            IsDeleted = false,
                            Name = "A set of boutique natural wood bathroom countertops",
                            Price = 199.00m,
                            TreeTypeId = new Guid("632bfa2f-aa06-4c1b-913d-33ef43a44d34")
                        });
                });

            modelBuilder.Entity("TableTree.Data.Models.ProductStore", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ProductId", "StoreId");

                    b.HasIndex("StoreId");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("TableTree.Data.Models.ShoppingCart", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOfProducts")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("TableTree.Data.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f69b658-4422-4bb6-94b1-46a5f146f826"),
                            Address = "Bulgaria, Sofia, Druzhba"
                        },
                        new
                        {
                            Id = new Guid("be64604e-12e3-4872-bd07-242f1e45d0f2"),
                            Address = "Bulgaria, Plovdiv, Trakiya"
                        },
                        new
                        {
                            Id = new Guid("8e37d43e-cdc4-48ca-ade3-63147766cbce"),
                            Address = "Bulgaria, Bourgas, Trakiya"
                        });
                });

            modelBuilder.Entity("TableTree.Data.Models.TreeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfTrees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("632bfa2f-aa06-4c1b-913d-33ef43a44d34"),
                            Name = "Tree"
                        },
                        new
                        {
                            Id = new Guid("133a6af3-1b7d-4d6e-aa41-33be63184766"),
                            Name = "Beech"
                        },
                        new
                        {
                            Id = new Guid("401dd5cd-c271-4960-84ce-0b364c96f039"),
                            Name = "Оак"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTree.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TableTree.Data.Models.Comment", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Comments")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTree.Data.Models.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TableTree.Data.Models.FavouriteProduct", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ClientsFavouriteProducts")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTree.Data.Models.Product", "Product")
                        .WithMany("FavouriteProductsClients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TableTree.Data.Models.Order", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TableTree.Data.Models.OrderItemInfo", b =>
                {
                    b.HasOne("TableTree.Data.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTree.Data.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TableTree.Data.Models.Product", b =>
                {
                    b.HasOne("TableTree.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTree.Data.Models.TreeType", "TreeType")
                        .WithMany("Products")
                        .HasForeignKey("TreeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("TreeType");
                });

            modelBuilder.Entity("TableTree.Data.Models.ProductStore", b =>
                {
                    b.HasOne("TableTree.Data.Models.Product", "Product")
                        .WithMany("ProductStores")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTree.Data.Models.Store", "Store")
                        .WithMany("StoreProducts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("TableTree.Data.Models.ShoppingCart", b =>
                {
                    b.HasOne("TableTree.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ClientsProducts")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TableTree.Data.Models.Product", "Product")
                        .WithMany("ProductsClients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TableTree.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("ClientsFavouriteProducts");

                    b.Navigation("ClientsProducts");

                    b.Navigation("Comments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TableTree.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TableTree.Data.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TableTree.Data.Models.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavouriteProductsClients");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductStores");

                    b.Navigation("ProductsClients");
                });

            modelBuilder.Entity("TableTree.Data.Models.Store", b =>
                {
                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("TableTree.Data.Models.TreeType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
